In [67]:
import pandas as pd

oline = pd.read_csv("../../data/raw/OLineData.csv")
data = pd.read_csv("../../data/processed/newdraft.csv")

In [68]:
oline.head()

,Year,Team,Adjusted Line yards,Unnamed: 3,Running Back Yards,Unnamed: 5,Power Success Rate,Unnamed: 7,Open Field Yards,Unnamed: 9,Second Level Yards,Unnamed: 11,Stuffed Rate,Unnamed: 13,Adjusted Sack Rate,Unnamed: 15,Sacks
0,2020,ARI,30,3.91,19,4.16,16,66%,16,0.74,27,1.08,25,18.60%,8,5.40%,29
1,2020,ATL,26,4.12,29,3.90,26,57%,26,0.55,30,1.03,16,17.00%,18,6.70%,41
2,2020,BAL,8,4.59,1,5.21,5,75%,1,1.24,9,1.30,5,14.10%,23,7.50%,32
3,2020,BUF,15,4.36,11,4.49,17,66%,9,0.87,13,1.26,15,16.90%,5,4.80%,27
4,2020,CAR,13,4.43,31,3.85,6,73%,32,0.32,19,1.17,13,16.30%,17,6.60%,36

In [69]:
oline = oline[["Year", "Team", "Adjusted Line yards", "Running Back Yards", "Stuffed Rate"]]
oline.columns = ["year", "team", "team_adjusted_line_yards", "team_running_back_yards", "team_stuffed_rate"]

In [70]:
oline

,year,team,team_adjusted_line_yards,team_running_back_yards,team_stuffed_rate
0,2020,ARI,30,19,25
1,2020,ATL,26,29,16
2,2020,BAL,8,1,5
3,2020,BUF,15,11,15
4,2020,CAR,13,31,13
...,...,...,...,...,...
786,1996,SEA,19,6,16
787,1996,SFO,11,13,20
788,1996,STL,22,21,22
789,1996,TAM,30,30,24
790,1996,WAS,8,9,10

In [71]:
merged = data.merge(oline, on=["year", "team"], how="left")

In [72]:
merged.isnull().sum()

Unnamed: 0                   0
year                         0
playername                   0
team                         0
age                          0
draft_yr                     0
draft_pos                    0
attempts                     0
yards_run                    0
tds_run                      0
longgain_run                 0
yardsperatt                  0
yardspergame_run             0
basesalarycap (10^8)         0
Percenthit (%)               0
caphit (M)                   0
cashspent (M)                0
g                            0
gs                           0
tgt                          0
rec                          0
catchpercent                 0
yards_rec                    0
yardsperrec                  0
tds_rec                      0
firstdowns                   0
longgain_rec                 0
yardspertarget               0
recpergame                   0
yardspergame_rec             0
fumbles                      0
team_adjusted_line_yards    15
team_running_back_yards     15
team_stuffed_rate           15
dtype: int64

In [75]:
merged.size

AttributeError: 'DataFrame' object has no attribute 'length'

In [66]:
merged.to_csv("../../data/processed/oline_merge.csv")